export const FACTIONS = {
  senate: {
    id: 'senate',
    name: 'The Senate',
    icon: '🏛️',
    color: '#6366f1',
    tooHighLabel: 'Oligarchic lock',
    tooHighDesc: 'The Senate purges you for overreach.',
    tooLowLabel: 'Constitutional crisis',
    tooLowDesc: 'You lose legitimacy and are ousted.',
  },
  military: {
    id: 'military',
    name: 'Military',
    icon: '⚔️',
    color: '#ef4444',
    tooHighLabel: 'Military coup',
    tooHighDesc: 'They no longer need you.',
    tooLowLabel: 'Collapse of order',
    tooLowDesc: 'Pirates and insurgents overwhelm borders.',
  },
  trade: {
    id: 'trade',
    name: 'Trade League',
    icon: '💰',
    color: '#f59e0b',
    tooHighLabel: 'Corporate capture',
    tooHighDesc: 'Your votes are bought and you are blackmailed.',
    tooLowLabel: 'Economic collapse',
    tooLowDesc: 'Hyperinflation and supply chain failure.',
  },
  coalition: {
    id: 'coalition',
    name: 'Alien Coalition',
    icon: '👽',
    color: '#10b981',
    tooHighLabel: 'Alien dominance',
    tooHighDesc: 'Human worlds placed under Coalition oversight.',
    tooLowLabel: 'Species conflict',
    tooLowDesc: 'War breaks out across the outer systems.',
  },
};
